### ISSUE TITLE
Activating extension 'Thinker.properties' failed: Could not find ffprobe executable

### ISSUE THREAD

**Issue by tjx666** [R35007/properties-vscode-extension#1]
<img width="408" alt="image" src="https://user-images.githubusercontent.com/41773861/205453890-b9aeaea9-5370-4b2a-9ebc-049604a567c7.png">

```
Thinker.properties: v10.2.0
Version: 1.73.1 (Universal)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T02:08:38.961Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.1.0
Sandboxed: No
```

**Comment by R35007** [comment]
Hi @tjx666 ,

Sorry for the trouble and Thanks for the error update.
Since I have developed this extension in a windows machine, I haven't faced this issue. 

With this new version [11.0.0](https://marketplace.visualstudio.com/items?itemName=Thinker.properties) the ffprobe path error will not stop the extension to run but you may still the not get the addition properties of an audio and video file like duration, dimensions, album, artist etc...

This new version also supports multiple selection properties.

For the mac users I have provided a setting `properties.settings.ffprobePath` where we can explicitly give the ffprobe executable path to get the additional properties of an audio and video.
But please make sure the FFmpegis installed in your system before providing the ffprobe path.
Please visit [FFmpeg](https://ffmpeg.org/download.html) site for more installation guide if you don't have FFmpeg installed in your system.

Please let me know if you need anything! Thanks :-)

**Comment by tjx666** [comment]
It now works
